# Generated by Django 4.2.7 on 2023-11-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review_product_review_stars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
        migrations.AddField(
            model_name='product',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
