# Generated by Django 4.2.7 on 2023-11-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_review_stars_product_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stars',
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
